### PR TITLE
Get schema

### PR DESCRIPTION
**Pull request by jeffbeagley**
I need to parse once and batch handle thousands of messages, and parsing the schema and decoding at the same time proved to be inefficient. Adding this function allows me to grab the schema once by ID and then iterate over messages to decode it. 

This was the quickest method I came up with, however I think your internal schema cache should be extended to cache the already parsed schema, and decode message could be converted to check for a parsed schema on each iteration. 

I don't believe this needs to be merged in as its incomplete, but wanted to use this to start the conversation of caching the schema.

### CODE REVIEW

**Comment by bencebalogh** [comment]
I agree the parsed schema should be store in the cache, that should be the default behavior.
Once that's implemented, wouldn't it solve your performance issue? After fetching the schema only you'd still have to `fromBuffer` on your messages.

If it's enough I can either do a PR or we should modify this one to store the parsed schema in the cache.

**Comment by jeffbeagley** [comment]
Agree on solving performance issues. I feel like the code for parsing the schema should be stripped out into its own module, and decode function made to reference that so I can get rid of the boolean flag to return the schema. 

I unfortunately won't have time to get to this in the next few weeks, but if no other PR is done by then I can get some work done on it.

**Comment by jeffbeagley** [comment]
After digesting your comment, the parsed schema could be stored in the cache and retrieved inside the decode function providing a performance increase for anyone already referencing decode. Is there a reason to parse every single message?

**Comment by bencebalogh** [comment]
There's no real reason I can think of, it's just something I missed during the initial implementation and hasn't come up since.
You've said you won't have time in the short term to look at this so I'll try to make time for it this weekend.

**Comment by bencebalogh** [comment]
Opened #11 , can you please check if I am missed anything?

**Comment by bencebalogh** [comment]
Closing in favor of #11

**Pull request closed without merging**
